import { roboto } from "@/fonts";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <link
                    href="https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css"
                    rel="stylesheet"
                ></link>
            </head>

            <body className={roboto.className}>{children}</body>
        </html>
    );
}
